version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: todo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      # db servisine Docker'ın dahili DNS ağı üzerinden bağlanıyoruz
      - MONGO_URI=mongodb://db:27017/todoapp
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: always
    ports:
      # Kullanıcı http://localhost üzerinden erişebilir
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
